In [1]:
import pandas as pd

In [2]:
df1 = pd.read_excel('IBEX35.xlsx')
df1

                                              Name   Symbol      Time
0   ACS Actividades de Construccion y Servicios SA   ACS.MC       NaN
1                                         Acerinox   ACX.MC       NaN
2               Banco Bilbao Vizcaya Argentaria SA  BBVA.MC  08:02:36
3                                        Bankinter   BKT.MC  08:06:44
4                                          Acciona   ANA.MC       NaN
5                                     Caixabank SA  CABK.MC       NaN
6                                           Enagas   ENG.MC  08:06:51
7                          Naturgy Energy Group SA  NTGY.MC  08:05:11
8                                       Grifols SA   GRF.MC       NaN
9                                        Ferrovial   FER.MC  08:04:31
10                           Redeia Corporacion SA   RED.MC  08:05:02
11                   Industria de Diseno Textil SA   ITX.MC  08:06:47
12                                          Repsol   REP.MC       NaN
13                                       Iberdrola   IBE.MC  08:05:07
14                                         Indra A   IDR.MC       NaN
15                                          Mapfre   MAP.MC       NaN
16                                      Telefonica   TEF.MC       NaN
17                                        Sacyr SA  SCYR.MC       NaN
18                            Banco de Sabadell SA   SAB.MC       NaN
19                                 Banco Santander   SAN.MC  08:06:56
20                        Inmobiliaria Colonial SA   COL.MC  08:07:05
21  International Consolidated Airlines Group S.A.   IAG.MC       NaN
22                                       Endesa SA   ELE.MC       NaN
23                                      Amadeus IT   AMS.MC       NaN
24                 Laboratorios Farmaceuticos ROVI  ROVI.MC  07:45:36
25                SOLARIA ENERGIA Y MEDIO AMBIENTE   SLR.MC  08:00:12
26                                         Fluidra   FDR.MC  08:04:32
27                                ArcelorMittal SA   MTS.MC  08:06:19
28                            Merlin Properties SA   MRL.MC       NaN
29                                         Logista   LOG.MC       NaN
30                                     Aena SME SA  AENA.MC  07:58:47
31                              Cellnex Telecom SA  CLNX.MC  08:05:47
32                                Unicaja Banco SA   UNI.MC       NaN
33      Corporacion Acciona Energias Renovables SA   ANE.MC  07:40:30
34                                  Puig Brands SA  PUIG.MC  07:51:26

In [3]:
dftest = pd.DataFrame()
dftest['test'] = df1['Name'].unique()
dftest.info()
# Observamos que tenemos 35 compañias distintas del IBEX35

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   test    35 non-null     object
dtypes: object(1)
memory usage: 412.0+ bytes

In [4]:
#Cramos un nuevo dataframe que tome como valores solamente lso tickers
df2 = df1['Symbol']
df2.head()

0     ACS.MC
1     ACX.MC
2    BBVA.MC
3     BKT.MC
4     ANA.MC
Name: Symbol, dtype: object

In [5]:
#Importamos la libreria encargada de bajarnos los historicos de los datos de la bolsa
from yahoo_fin.stock_info import get_data, tickers_sp500, tickers_nasdaq, tickers_other, get_quote_table

Warning - Certain functionality
             requires requests_html, which is not installed.

             Install using:
             pip install requests_html

             After installation, you may have to restart your Python session.

In [6]:
datos = {f'{nombre}': None for nombre in df2} #Sirve para algo?

In [7]:
datos

{'ACS.MC': None,
 'ACX.MC': None,
 'BBVA.MC': None,
 'BKT.MC': None,
 'ANA.MC': None,
 'CABK.MC': None,
 'ENG.MC': None,
 'NTGY.MC': None,
 'GRF.MC': None,
 'FER.MC': None,
 'RED.MC': None,
 'ITX.MC': None,
 'REP.MC': None,
 'IBE.MC': None,
 'IDR.MC': None,
 'MAP.MC': None,
 'TEF.MC': None,
 'SCYR.MC': None,
 'SAB.MC': None,
 'SAN.MC': None,
 'COL.MC': None,
 'IAG.MC': None,
 'ELE.MC': None,
 'AMS.MC': None,
 'ROVI.MC': None,
 'SLR.MC': None,
 'FDR.MC': None,
 'MTS.MC': None,
 'MRL.MC': None,
 'LOG.MC': None,
 'AENA.MC': None,
 'CLNX.MC': None,
 'UNI.MC': None,
 'ANE.MC': None,
 'PUIG.MC': None}

In [8]:
#Creamos un loop que me itere por cada ticker que aparece en 
count = 1
for ticker in df2:
    print(ticker + ' ' + str(count))
    locals()[ticker] =  get_data(ticker, start_date='01/01/2021')
    locals()[ticker].to_csv('data/'+ticker+'.csv', encoding= 'utf-8')
    count= count + 1

ACS.MC 1
ACX.MC 2
BBVA.MC 3
BKT.MC 4
ANA.MC 5
CABK.MC 6
ENG.MC 7
NTGY.MC 8
GRF.MC 9
FER.MC 10
RED.MC 11
ITX.MC 12
REP.MC 13
IBE.MC 14
IDR.MC 15
MAP.MC 16
TEF.MC 17
SCYR.MC 18
SAB.MC 19
SAN.MC 20
COL.MC 21
IAG.MC 22
ELE.MC 23
AMS.MC 24
ROVI.MC 25
SLR.MC 26
FDR.MC 27
MTS.MC 28
MRL.MC 29
LOG.MC 30
AENA.MC 31
CLNX.MC 32
UNI.MC 33
ANE.MC 34
PUIG.MC 35